x-better-auth-secret: &better_auth_secret "OKXBVIAKHUmQ9wOlAm7CTakv5ZmObP589ta5crKFOtBtykcd7SpToRBqBb5HOHbK"

services:
  app:
    build:
      context: .
      args:
        BETTER_AUTH_SECRET: *better_auth_secret
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5401:5401"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: educarrer2505

      DATABASE_URL: "postgresql://educarrer:2505@postgres:5432/edu_carrer_web"

      NEXT_BETTER_AUTH_SECRET: *better_auth_secret
      NEXT_BETTER_AUTH_URL: "http://localhost:5401"

      BETTER_AUTH_SECRET: *better_auth_secret
      BETTER_AUTH_URL: "http://localhost:5401"

      NEXT_PUBLIC_API_URL: "http://localhost:5401"
      NEXT_PUBLIC_AMBIENTE: "dev"

      OPENAI_API_KEY: ${OPENAI_API_KEY}

      PORT: "5401"

  redis:
    image: redis
    command: redis-server --requirepass educarrer2505
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: educarrer
      POSTGRES_PASSWORD: 2505
      POSTGRES_DB: edu_carrer_web
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U educarrer"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: