version: '3.9'

services:
  app:
    build: .
    ports:
      - "5401:5401"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: educarrer2505

      DATABASE_URL: "postgresql://postgres:2505@postgres:5432/edu_carrer_web"

      NEXT_BETTER_AUTH_SECRET: "OKXBVIAKHUmQ9wOlAm7CTakv5ZmObP589ta5crKFOtBtykcd7SpToRBqBb5HOHbK"
      NEXT_BETTER_AUTH_URL: "http://localhost:5401"

      BETTER_AUTH_SECRET: "OKXBVIAKHUmQ9wOlAm7CTakv5ZmObP589ta5crKFOtBtykcd7SpToRBqBb5HOHbK"
      BETTER_AUTH_URL: "http://localhost:5401"

      NEXT_PUBLIC_API_URL: "http://localhost:5401"
      NEXT_PUBLIC_AMBIENTE: "dev"

      PORT: "5401"

  redis:
    image: redis
    command: redis-server --requirepass educarrer2505
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2505
      POSTGRES_DB: edu_carrer_web
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: